version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_NAME=task_management
      - DB_USER=user
      - DB_PASS=password
      - DB_HOST=db
      - JWT_SECRET=your_jwt_secret

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
